
# --- BASE HUGO CONFIGURATION ---
baseURL: https://mcndt.dev/
languageCode: en-us
title: Maxime Cannoodt
theme: PaperMod
enableEmoji: true
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

author:
  name: Maxime Cannoodt
  image: profile-pic.jpg
  bio: "I'm a computer science engineer with interest in a wide range of 
        topics, including productivity, PKM, artificial intelligence, product 
        development and game design."
  links:
    - github: 'https://github.com/mcndt'
    - linkedin: 'https://www.linkedin.com/in/maxime-cannoodt-7b2697192/?locale=en_US'
    # - twitter: 'https://twitter.com/maximio_'


# --- NAVIGATION MENUS ---
menu: 
  main:
  - name: "Blog"
    url: "/posts/"
    weight: "10"
  - name: "Projects"
    url: "/projects/"
    weight: "20"
  # - name: "Resume"
  #   url: "/resume/"
  #   weight: "30"
  - name: "About"
    url: "/about/"
    weight: "30"
  - name: "Archive"
    url: "/archive/"
    weight: "40"

# --- THEME CONFIGURATION (theme=PaperMod) --- #
params:
  description: "Blog of Maxime Cannoodt, software and ML engineer from Ghent, Belgium."
  author: "Maxime Cannoodt"

  label:
    text: "mcndt"
    # icon: 'profile-cropped.jpg'
    # iconHeight: 35

  defaultTheme: auto
  ShowReadingTime: false
  ShowBreadCrumbs: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  disableAnchoredHeadings: true

  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/mcndt"
    # - name: "Twitter"
    #   url: "https://twitter.com/maximio_"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/maxime-cannoodt-7b2697192/?locale=en_US"

  homeInfoParams:
    Title: "mcndt"
    Content: "I'm a computer science engineer with interest in a wide range of 
        topics, including productivity, PKM, artificial intelligence, product 
        development and game design.
        <br><br>
        On my blog, you will find posts about personal projects, 
        workflow and productivity, and reviews.
        Find out more about me <a style='box-shadow: 0 1px' href='/about'>here</a>."

    imageUrl: "/profile-pic.jpg" # optional
    imageTitle: "portrait photo of me" # optional


  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
